# Generated by Django 4.2.4 on 2023-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_buyer_products_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
