# Generated by Django 4.2.4 on 2023-09-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_buyer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-order_date']},
        ),
    ]
